nywa	ukinywa	V;FIN;SUBJ;COM;PST;3;SG;LGSPEC6
pa	imekupa	V;FIN;IND;PST;PRF;3;SG;LGSPEC5
andika	yaliandika	V;FIN;IND;PST;3;PL;LGSPEC3
sumbua	zikisumbua	V;FIN;SUBJ;COM;PST;3;PL;LGSPEC6
soma	zimesoma	V;FIN;IND;PST;PRF;3;PL;LGSPEC6
eua	umeeua	V;FIN;IND;PST;PRF;2;SG
amba	mnaamba	V;FIN;IND;PRES;2;PL
baki	hubaki	V;FIN;IND;HAB;SG
sumbua	yakisumbua	V;FIN;SUBJ;COM;PST;3;PL;LGSPEC3
endesha	yataendesha	V;FIN;IND;FUT;3;PL;LGSPEC3
andika	naandika	V;FIN;IND;IND;INDF1;SG
endesha	yangeendesha	V;FIN;IND;COND;PRES;3;PL;LGSPEC3
endesha	iendeshe	V;FIN;IND;PST;3;SG;LGSPEC5
amba	laamba	V;FIN;IND;INDF3;SG;LGSPEC3
tatua	twatatua	V;FIN;INDF1;PL
sumbua	kikisumbua	V;FIN;SUBJ;COM;PST;3;SG;LGSPEC4
zima	mzima	ADJ;SG;LGSPEC2
kuna	ilikuna	V;FIN;IND;PST;3;PL;LGSPEC2
faa	zinafaa	V;FIN;IND;PRES;3;PL;LGSPEC5
andikisha	uandikishe	V;FIN;IND;PST;3;SG;LGSPEC2
safiri	asafiri	V;FIN;IND;IND;INDF3;SG;LGSPEC1
bariki	tukabariki	V;FIN;IND;LGSPEC10;1;PL
endesha	kimeendesha	V;FIN;IND;PST;PRF;3;SG;LGSPEC4
badilia	vitabadilia	V;FIN;IND;FUT;3;PL;LGSPEC4
baki	amebaki	V;FIN;IND;PST;PRF;3;SG;LGSPEC1
lipia	vikilipia	V;FIN;SUBJ;COM;PST;3;PL;LGSPEC4
nuka	akinuka	V;FIN;SUBJ;COM;PST;3;SG;LGSPEC1
enda	zingalikwenda	V;FIN;IND;COND;PST;3;PL;LGSPEC5
fua	tumefua	V;FIN;IND;PST;PRF;1;PL
kuna	kilikuna	V;FIN;IND;PST;3;SG;LGSPEC4
lala	wakalala	V;FIN;IND;LGSPEC10;3;PL;LGSPEC1
andikisha	itaandikisha	V;FIN;IND;FUT;3;PL;LGSPEC2
ona	zitaona	V;FIN;IND;FUT;3;PL;LGSPEC5
andaa	zinaandaa	V;FIN;IND;PRES;3;PL;LGSPEC6
piga	akipiga	V;FIN;SUBJ;COM;PST;3;SG;LGSPEC1
lipa	zililipa	V;FIN;IND;PST;3;PL;LGSPEC6
amba	nitaamba	V;FIN;IND;FUT;1;SG
nywa	ingekunywa	V;FIN;IND;COND;PRES;3;PL;LGSPEC2
ona	yangaliona	V;FIN;IND;COND;PST;3;PL;LGSPEC3
zuri	muzuri	ADJ;PL;LGSPEC9
sumbua	imesumbua	V;FIN;IND;PST;PRF;3;SG;LGSPEC5
ema	njema	ADJ;SG;LGSPEC4
baki	zikabaki	V;FIN;IND;LGSPEC10;3;PL;LGSPEC5
tatua	zikatatue	V;FIN;SUBJ;LGSPEC10;3;PL;LGSPEC6
badilia	ibadilie	V;FIN;SUBJ;PST;3;PL;LGSPEC2
fua	wafua	V;FIN;IND;IND;INDF3;SG;LGSPEC2
nunua	ungenunua	V;FIN;IND;COND;PRES;2;SG
badili	labadili	V;FIN;IND;INDF3;SG;LGSPEC3
pana	pana	ADJ;PL;LGSPEC5
kana	tukikana	V;FIN;SUBJ;COM;PST;1;PL
badili	tumebadili	V;FIN;IND;PST;PRF;1;PL
faa	ifae	V;FIN;SUBJ;PST;3;PL;LGSPEC2
ona	imeona	V;FIN;IND;PST;PRF;3;SG;LGSPEC5
penda	yangalipenda	V;FIN;IND;COND;PST;3;PL;LGSPEC3
andaa	ukaandae	V;FIN;SUBJ;LGSPEC10;3;SG;LGSPEC6
andikisha	zikaandikishe	V;FIN;SUBJ;LGSPEC10;3;PL;LGSPEC6
endesha	akaendesha	V;FIN;IND;LGSPEC10;3;SG;LGSPEC1
penda	kingalipenda	V;FIN;IND;COND;PST;3;SG;LGSPEC4
kwepa	imekwepa	V;FIN;IND;PST;PRF;3;PL;LGSPEC2
ongea	vitaongea	V;FIN;IND;FUT;3;PL;LGSPEC4
afiki	ukiafiki	V;FIN;SUBJ;COM;PST;3;SG;LGSPEC6
kuna	mmekuna	V;FIN;IND;PST;PRF;2;PL
lala	ukilala	V;FIN;SUBJ;COM;PST;2;SG
nuka	ingalinuka	V;FIN;IND;COND;PST;3;SG;LGSPEC5
nunua	vitanunua	V;FIN;IND;FUT;3;PL;LGSPEC4
ona	wakiona	V;FIN;SUBJ;COM;PST;3;PL;LGSPEC1
baki	zilibaki	V;FIN;IND;PST;3;PL;LGSPEC5
umba	ingaliumba	V;FIN;IND;COND;PST;3;SG;LGSPEC5
jeuri	kujeuri	ADJ;SG;LGSPEC6
nuka	wakanuka	V;FIN;IND;LGSPEC10;3;PL;LGSPEC1
pa	lingalikupa	V;FIN;IND;COND;PST;3;SG;LGSPEC3
kana	zikikana	V;FIN;SUBJ;COM;PST;3;PL;LGSPEC6
bariki	mtabariki	V;FIN;IND;FUT;2;PL
soma	ukasome	V;FIN;SUBJ;LGSPEC10;2;SG
kuna	mkikuna	V;FIN;SUBJ;COM;PST;2;PL
andikisha	yangeandikisha	V;FIN;IND;COND;PRES;3;PL;LGSPEC3
andika	uandike	V;FIN;IND;PST;3;SG;LGSPEC2
piga	yapiga	V;FIN;IND;INDF3;SG;LGSPEC5
tatua	ungetatua	V;FIN;IND;COND;PRES;2;SG
lala	tulilala	V;FIN;IND;PST;1;PL
umba	zitaumba	V;FIN;IND;FUT;3;PL;LGSPEC5
badili	alibadili	V;FIN;IND;PST;3;SG;LGSPEC1
andikisha	vikaandikishe	V;FIN;SUBJ;LGSPEC10;3;PL;LGSPEC4
lala	linalala	V;FIN;IND;PRES;3;SG;LGSPEC3
amba	tukaamba	V;FIN;IND;LGSPEC10;1;PL
lala	zilale	V;FIN;SUBJ;PST;3;PL;LGSPEC5
ja	alikuja	V;FIN;IND;PST;3;SG;LGSPEC1
penda	yakapenda	V;FIN;IND;LGSPEC10;3;PL;LGSPEC3
kuna	ukakuna	V;FIN;IND;LGSPEC10;3;SG;LGSPEC2
fupi	mifupi	ADJ;PL;LGSPEC2
fa	ungekufa	V;FIN;IND;COND;PRES;3;SG;LGSPEC6
ja	wakaje	V;FIN;SUBJ;LGSPEC10;3;PL;LGSPEC1
lala	lililala	V;FIN;IND;PST;3;SG;LGSPEC3
pa	wapa	V;FIN;IND;IND;INDF3;SG;LGSPEC2
fa	kufa	V;NFIN
penda	mngalipenda	V;FIN;IND;COND;PST;2;PL
fua	kingalifua	V;FIN;IND;COND;PST;3;SG;LGSPEC4
kuna	ikakune	V;FIN;SUBJ;LGSPEC10;3;PL;LGSPEC2
changa	kuchanga	ADJ;PL;LGSPEC6
zuri	kuzuri	ADJ;PL;LGSPEC6
